
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders
    ports: 
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongo-inventory:
    image: mongo:4.4
    container_name: mongo-inventory
    environment:
      MONGO_URI: ${mongo_uri}
    ports:
      - "27017:27017"
    volumes:
      - mongo-inventory-data:/data/db

  mongo-users:
    image: mongo:4.4
    container_name: mongo-users
    environment:
      - MONGO_URI= value
    volumes: 
      - mongo-users-data:/data/db

  orders-service:
    build: ./services/orders
    ports:
      - "3002:3002"
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders
  inventory-service:
    build: ./services/inventory
    ports:
      - "3001:3001"
    depends_on:
      - mongo-inventory
  users-service:
    build: ./services/users
    ports: 
      - "3003:3003"
    depends_on:
      - mongo-users
volumes:
  postgres-data:
  mongo-inventory-data:
